---
abstract: 'Create a Boolean Truth Table'
author:
  - 'John M. Gamble <jgamble@cpan.org>'
build_requires:
  Test::Deep: '1.12'
  Test::More: '0'
  Test::Output: '0'
configure_requires:
  Module::Build: '0.4224'
dynamic_config: 0
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
keywords:
  - boolean
  - boolean-algebra
  - logic
  - truth-table
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Logic-TruthTable
provides:
  Logic::TruthTable:
    file: lib/Logic/TruthTable.pm
    version: '1.01'
  Logic::TruthTable::Convert81:
    file: lib/Logic/TruthTable/Convert81.pm
    version: '1.01'
  Logic::TruthTable::Util:
    file: lib/Logic/TruthTable/Util.pm
    version: '1.01'
requires:
  Algorithm::QuineMcCluskey: '1'
  Carp: '0'
  Convert::Base81: '1.00'
  JSON: '2.61'
  Logic::Minimizer: '1.00'
  Module::Runtime: '0.014'
  Moose: '2.16'
  Text::CSV: '0'
  namespace::autoclean: '0.16'
  perl: v5.16.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jgamble/Logic-TruthTable
version: '1.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
